# @prettier
on: push

name: 'Test Find Issue Key'

jobs:
  test-find-issue-key:
    name: 'Find Issue Key'
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'github-action-jira-find-issue-keys'
      - name: Test
        run: |
          ls -lah
          ls -lah github-action-jira-find-issue-keys
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL || secrets.JIRA_EMAIL}}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN || secrets.JIRA_TOKEN}}

      - name: 'Find Issue Key'
        id: find
        uses: ./github-action-jira-find-issue-keys
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          github-token: ${{github.token}}
          from: string
          string: DVPS-342 | will search in branch name

      - name: 'Find issue info'
        shell: bash
        env:
          ISSUE_FOUND: ${{ steps.find.outputs.issue }}
        run: |
          if [[ "${ISSUE_FOUND}" == "DVPS-342" ]];then
            echo "::info:: Issue ${ISSUE_FOUND} was found"
          else
            echo "::error:: Find issue from string failed"
          fi
